[package]
name = "penumbra-cometmock-driver"
version = "0.61.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Penumbra dependencies
penumbra-proto = { path = "../../proto", features = ["rpc"] }
penumbra-transaction = { path = "../../core/transaction" }

# External dependencies
anyhow = "1"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1"
tendermint = "0.33.0"
tendermint-config = "0.33.0"
tendermint-light-client-verifier = "0.33.0"
tendermint-proto = "0.33.0"
tendermint-rpc = { version = "0.33.0", features = ["http-client"] }
tokio = { version = "1.22", features = ["full"] }
url = "2"
