[workspace]

exclude = [
    "tools/proto-compiler",
    "tools/parameter-setup",
]

# Also remember to add to deployments/scripts/rust-docs
members = [
  "decaf377-fmd",
  "decaf377-ka",
  "eddy",
  "proto",
  "chain",
  "app",
  "crypto",
  "custody",
  "measure",
  "narsil",
  "storage",
  "tct",
  "tct-property-test",
  "tct-visualize",
  "tendermint-proxy",
  "tower-trace",
  "transaction",
  "wallet",
  "view",
  "pd",
  "pclientd",
  "pcli",
  "proof-params",
  "wasm",
]

# Optimize for small binaries in just the wasm crate.
[profile.release.package.penumbra-wasm]
opt-level = "s"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.0.5"
# The preferred Rust toolchain to use in CI (rustup toolchain syntax)
rust-toolchain-version = "1.67.1"
# CI backends to support (see 'cargo dist generate-ci')
ci = ["github"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-pc-windows-msvc", "aarch64-apple-darwin"]

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
