[workspace]

# Also remember to add to .github/workflows/notes.yml
members = [
  "decaf377-fmd",
  "decaf377-ka",
  "proto",
  "crypto",
  "chain",
  "stake",
  "transaction",
  "wallet",
  "pd",
  "pcli",
  "tct",
  "ibc",
]

[patch.crates-io]
# The "ours" branch is based off of v0.3.0
ark-ff = { git = "https://github.com/penumbra-zone/algebra", branch = "ours" }
ark-serialize = { git = "https://github.com/penumbra-zone/algebra", branch = "ours" }
# temp
decaf377 = { git = "https://github.com/penumbra-zone/decaf377", branch = "jf-proof" }
ark-ed-on-bls12-377 = { git = "https://github.com/arkworks-rs/curves", rev = "677b4ae751a274037880ede86e9b6f30f62635af" }
ark-bls12-377 = { git = "https://github.com/arkworks-rs/curves", default-features = false, features = ["curve"], rev = "677b4ae751a274037880ede86e9b6f30f62635af" }
