{{ $count := (.Values.numFullNodes | int) }}
{{ $svc_name := printf "%s-rpc-backends" (include "penumbra.fullname" $) }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ $svc_name }}
  labels:
    app: {{ $svc_name }}
    {{- include "penumbra.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  type: ClusterIP
  selector:
    type: fullnode
    app.kubernetes.io/instance: {{ include "penumbra.fullname" . }}
  ports:
    - protocol: TCP
      port: 26657
      targetPort: rpc
      name: tm-rpc
    - protocol: TCP
      port: 8080
      targetPort: grpc
      name: pd-grpc
