name: Smoke Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  smoke_test:
    runs-on: buildjet-16vcpu-ubuntu-2004
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    environment: smoke-test
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Load rust cache
        uses: astriaorg/buildjet-rust-cache@v2.5.1

      - name: Install cometbft binary
        run: |
          COMETBFT_VERSION="0.37.2"
          curl -L -O "https://github.com/cometbft/cometbft/releases/download/v${COMETBFT_VERSION}/cometbft_${COMETBFT_VERSION}_linux_amd64.tar.gz"
          tar -xzf "cometbft_${COMETBFT_VERSION}_linux_amd64.tar.gz" cometbft
          mkdir -p $HOME/bin
          cp cometbft $HOME/bin
          echo $PATH
          export PATH=$HOME/bin:$PATH
          which cometbft
          cometbft version

      # Build CometMock from source
      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Build cometmock
        run: |
          cometmock_gitref="v0.37.x"
          git clone --depth 1 --branch "$cometmock_gitref"  https://github.com/informalsystems/CometMock ../cometmock
          cd ../cometmock || exit 1
          mkdir -p $HOME/bin
          go build -o $HOME/bin/cometmock ./cometmock
          export PATH=$HOME/bin:$PATH
          which cometmock

      - name: Run the smoke test suite
        run: |
          export PATH="$HOME/bin:$PATH"
          ./deployments/scripts/smoke-test.sh
        env:
          TESTNET_RUNTIME: 2m
